---
openapi: 3.0.3
info:
  title: drk-storage
  description: API for storing drawing data
  version: 0.0.1
servers:
  - url: http://localhost:8082
    description: Inferred URL
tags:
  - name: Document Controller
    description: Document controller
  - name: Document Details Controller
    description: Document Details controller
  - name: Iteration Controller
    description: Iteration controller
  - name: File Controller
    description: File controller
paths:
  '/documents':
    get:
      tags:
        - Document Controller
      summary: Get all documents
      operationId: getDocumentsUsingGET
      responses:
        '200':
          description: There is OK response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Documents'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - Authorization:
            - global
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    Customer:
      title: Customer
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    Department:
      title: Department
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    Document:
      title: Document
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        article:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        department:
          $ref: '#/components/schemas/Department'
        iteration:
          $ref: '#/components/schemas/Iteration'
        partOf:
          type: string
          format: uuid
    Documents:
      title: Documents
      type: array
      items:
        $ref: '#/components/schemas/Document'
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        cause:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/InnerError'
        i18nKey:
          type: string
        message:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: object
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum:
            - SERVER
            - SECURITY
            - VALIDATION
            - REQUEST
            - AUTHENTICATION
    File:
      title: File
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - PDF
            - STEP
            - DRAWING
            - MODEL
            - CAST_DRAWING
            - CAST_MODEL
            - TECH_REQ
            - NOTE
        uploadDate:
          type: string
          format: date-time
        payload:
          type: string
          format: byte
    InnerError:
      title: InnerError
      type: object
      properties:
        target:
          type: string
        message:
          type: string
    Iteration:
      title: Iteration
      type: object
      properties:
        id:
          type: string
          format: uuid
        number:
          type: integer
          format: int64
        reason:
          type: string
        description:
          type: string
        creator:
          $ref: '#/components/schemas/User'
        verifier:
          $ref: '#/components/schemas/User'
        iterationPayload:
          $ref: '#/components/schemas/IterationPayload'
    IterationPayload:
      title: IterationPayload
      type: object
      additionalProperties:
        $ref: '#/components/schemas/File'
    User:
      title: User
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - ADMIN
            - DEV
            - USER
        department:
          $ref: '#/components/schemas/Department'